name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - run: curl "https://github.com/"